nev = input ('Hogy tisztelhetem fényeségedet?')
print('Üdvüzöllek, nagyságos', név, '!', sep='')
szam1 = input('Mely szám a legkedvesebb szívednek?')
szam1 = int(szam1)
szam2 = int(input('S melyik légyen a második kedvenced a számok végtelen sokaságából?'))
print('Eme két szem szorzata pediglen?' , szam1*szam2, 'lészen')

nev = input('Mi a neved?')
nap = input('Milyen nap van ma?')
print('Üdvözlöm ezen a szép'nap,-n,kedves , nev,sep = '')
